baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = ""
theme = "hugo-theme-learn"

metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false


[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Documentation for Hugo Learn Theme"
  author = "Mathieu Cornic"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  disableLandingPageButton = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = ""
  #themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]
