site_name: Preparation Checklist
docs_dir: "docs"
#copyright: "Copyright &copy; 2022"
#site_url: "https://aws-observability.github.io/terraform-aws-observability-accelerator/"
#repo_name: "aws-observability/terraform-aws-observability-accelerator"
#repo_url: "https://github.com/aws-observability/terraform-aws-observability-accelerator"

extra_css:
  - "stylesheet/style.css"

theme:
  logo: images/java-logo.png
  #favicon: images/aws-favicon.png
  name: material
  font:
    text: Fira Sans
  #custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - search.highlight
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.path
    - navigation.indexes
 

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - HTML and CSS:
      - HTML: html-css/html.md
      - CSS: html-css/css.md
      - CSS layout: html-css/css-layout.md
  - Java:
      - OOPs: java/oops.md
      - Optional Class: java/optional-class.md
  - Spring:
      - Spring Basic: spring/spring-basic.md
      - Spring MVC: spring/spring-mvc/index.md
      - Spring Boot: spring/spring-boot/index.md

markdown_extensions:
  - toc:
      title: On this page
  - def_list

plugins:
  - search
